const SnakeNamingStrategy = require('typeorm-naming-strategies')
  .SnakeNamingStrategy;

module.exports = [
  {
    name: 'development',
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'postgres',
    password: 'postgres',
    database: 'phonebook-api-dev',
    synchronize: true,
    logging: true,
    entities: ['src/entity/**/*'],
    migrations: ['src/migration/**/*'],
    subscribers: ['src/subscriber/**/*'],
    namingStrategy: new SnakeNamingStrategy(),
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
  {
    name: 'stage',
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'postgres',
    password: 'postgres',
    database: 'phonebook-api-test',
    synchronize: false,
    logging: true,
    entities: ['src/entity/**/*.ts'],
    migrations: ['src/migration/**/*.ts'],
    subscribers: ['src/subscriber/**/*.ts'],
    namingStrategy: new SnakeNamingStrategy(),
    cli: {
      entitiesDir: 'src/entity',
      migrationsDir: 'src/migration',
      subscribersDir: 'src/subscriber',
    },
  },
  {
    name: 'production',
    type: 'postgres',
    url: process.env.DATABASE_URL,
    synchronize: false,
    logging: false,
    entities: ['dist/src/entity/**/*.js'],
    migrations: ['dist/src/migration/**/*.js'],
    subscribers: ['dist/src/subscriber/**/*.js'],
    namingStrategy: new SnakeNamingStrategy(),
    cli: {
      entitiesDir: 'dist/src/entity',
      migrationsDir: 'dist/src/migration',
      subscribersDir: 'dist/src/subscriber',
    },
  },
  {
    name: 'ci',
    type: 'postgres',
    host: 'db',
    port: 5432,
    username: 'postgres',
    password: 'postgres',
    database: 'phonebook-api-test-dev',
    synchronize: true,
    logging: false,
    entities: ['dist/entity/**/*.js'],
    migrations: ['dist/migration/**/*.js'],
    subscribers: ['dist/subscriber/**/*.js'],
    namingStrategy: new SnakeNamingStrategy(),
    cli: {
      entitiesDir: 'dist/entity',
      migrationsDir: 'dist/migration',
      subscribersDir: 'dist/subscriber',
    },
  },
];
